version: "3.9"
services:
  ut99-server:
    image: roemer/ut99-server:latest
    volumes:
      - ut99-data:/ut-data
    ports:
      # Webadmin
      - 5580:5580/tcp
      # Game Play
      - 7777:7777/udp
      # Server Querying
      - 7778:7778/udp
      - 7779:7779/udp
      - 7780:7780/udp
      - 7781:7781/udp
      # LAN Discovery
      - 8777:8777/udp
      # Server Announcement
      - 27500:27500/tcp
      - 27500:27500/udp
      - 27900:27900/tcp
      - 27900:27900/udp
    environment:
      - UT_SERVERURL="CTF-Face?game=BotPack.CTFGame?mutator=MVES.MapVote,FlagAnnouncementsV2.FlagAnnouncements,WhoPushedMe.WhoPushedMe"
      - UT_SERVERNAME="// Agora Road`s Unreal Tournament //"
      - UT_ADMINNAME="Vince"
      - UT_ADMINEMAIL="binsu@waifu.club"
      - UT_MOTD1="Frag Nights every Friday @ 22:00 EST (GMT-5)"
      - UT_MOTD2="Agora Road members only!"
      - UT_ADMINPWD="Nice try :)"
      - UT_WEBADMINUSER="Aegean"
      - UT_WEBADMINPWD="Nice try :)"
      - UT_GAMEPWD="Ag0raCHANis_myW1F3"
volumes:
  ut99-data:
